import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import head from "next/head";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
  <title>Minishop - Free Bootstrap 4 Template by Colorlib</title>
  <meta charSet="utf-8" />
  <meta
    name="viewport"
    content="width=device-width, initial-scale=1, shrink-to-fit=no"
  />
  <link
    href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800"
    rel="stylesheet"
  />
  <link rel="stylesheet" href="css/open-iconic-bootstrap.min.css" />
  <link rel="stylesheet" href="css/animate.css" />
  <link rel="stylesheet" href="css/owl.carousel.min.css" />
  <link rel="stylesheet" href="css/owl.theme.default.min.css" />
  <link rel="stylesheet" href="css/magnific-popup.css" />
  <link rel="stylesheet" href="css/aos.css" />
  <link rel="stylesheet" href="css/ionicons.min.css" />
  <link rel="stylesheet" href="css/bootstrap-datepicker.css" />
  <link rel="stylesheet" href="css/jquery.timepicker.css" />
  <link rel="stylesheet" href="css/flaticon.css" />
  <link rel="stylesheet" href="css/icomoon.css" />
  <link rel="stylesheet" href="css/style.css" />
</head>

      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
  <Script src="js/jquery.min.js"></Script>
  <Script src="js/jquery-migrate-3.0.1.min.js"></Script>
  <Script src="js/popper.min.js"></Script>
  <Script src="js/bootstrap.min.js"></Script>
  <Script src="js/jquery.easing.1.3.js"></Script>
  <Script src="js/jquery.waypoints.min.js"></Script>
  <Script src="js/jquery.stellar.min.js"></Script>
  <Script src="js/owl.carousel.min.js"></Script>
  <Script src="js/jquery.magnific-popup.min.js"></Script>
  <Script src="js/aos.js"></Script>
  <Script src="js/jquery.animateNumber.min.js"></Script>
  <Script src="js/bootstrap-datepicker.js"></Script>
  <Script src="js/scrollax.min.js"></Script>
  <Script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></Script>
  <Script src="js/google-map.js"></Script>
  <Script src="js/main.js"></Script>
    </html>
  );
}
